server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ayddb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        #TODO: change to 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/ask-your-document

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    ollama:
      base-url: http://localhost:11434
      embedding:
        enabled: true
        model: nomic-embed-text
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/schema-postgresql.sql
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        initialize-schema: true
        collection-name: ask-your-document

    # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: document-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ayd.dto

  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379

  # Cache configuration
#  cache:
#    type: redis
#    redis:
#      time-to-live: 3600000  # 1 hour in milliseconds
#      cache-null-values: false

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

#Actuator with readiness and liveness
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#Custom application properties
application:
  ai-mode: true
  chat-memory-max-messages: 10
  models:
    openai:
      - gpt-5
      - gpt-5-mini
    ollama:
      - llama3.1
  frontend: http://localhost:5173
  kafka:
    document-upload-topic: document-upload-topic
  keycloak:
    realm: ask-your-document
    server-url: http://localhost:7080
    client-id: ask-your-document-backend
    client-secret: 4vM9duLGyZasgPTig1OoKRHZ33Vv5Qpo
  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: ask-your-document
    minio-file-delimiter: /
  query-transform: false
  ai-input-size: 5
  reranker:
    rerank: false
    reranker-url: http://localhost:8001
    minScoreThreshold: 0.1
  vector-store:
    top-k: 5
    similarity-threshold: 0.2
  semantic-cache:
    similarity-threshold: 0.9


logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
